### ISSUE TITLE
why does yadifa not use radix tree as zone data structure ?

### ISSUE THREAD

**Issue by zhishupp** [yadifa/yadifa#1]
I noticed YADIFA using AVL tree as its zone data structure, 
but NSD using radix tree and KNOT using HAT-trie, 
so why does YADIFA not use a higher performance data structure ?

**Comment by yadifa** [comment]
It depends on what is construed as performance.  The AVL is the most efficient data structure for our needs (the zone could be summarized as a hash table of AVL trees of lists)

Several parameters are to be taken into account.  Speed is one of course, and we are pretty happy about our seek times, but memory usage is also a chief concern.

**Comment by zhishupp** [comment]
okay, thanks.
