### ISSUE TITLE
Why are CNAME chains not followed?

### ISSUE THREAD

**Issue by SivaKesava1** [yadifa/yadifa#10]
Hi,

I was checking out YADIFA with some test zone files and provided it the following zone file:

|  	|  	|  	|  	|
|-	|-	|-	|-	|
| example.com. 	| 500 | SOA 	| ns1.outside.com. root.example.com. 3 604800 86400 2419200 604800 	|
| example.com. 	| 500 | NS 	| ns1.outside.com.  	|
|b.c.example.com. 	| 500 | CNAME | l.c.example.com. 	|
|l.c.example.com. 	| 500| CNAME 	| g.c.example.com.  	|
|g.c.example.com. 	| 500| A | 1.1.1.1|

For the query _<b.c.example.com. , A>_, the YADIFA server returns the following response:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "b.c.campus.edu. IN A",
          ";ANSWER",
          "b.c.campus.edu. 500 IN CNAME l.c.campus.edu.",
          ";AUTHORITY",
          ";ADDITIONAL"
```

**Expected behavior**
[RFC 1034 3.6.2](https://tools.ietf.org/html/rfc1034#section-3.6.2) does state 'CNAME chains should be followed,' and the server should return all the last three records. Other implementations like BIND, Knot, and PowerDNS return all the records. I looked up the documentation and did not find any reasoning as to why YADIFA does not follow CNAME chains. 
Any response would be helpful and appreciated.

**Comment by edfeu** [comment]
Thank you for reporting this issue.
The rerun of the query was incorrectly disabled, the issue is fixed and will be updated on github on our next update of the code.
