### ISSUE TITLE
Non-existent CNAME target in the same zone should be returned with NXDOMAIN instead of NOERROR

### ISSUE THREAD

**Issue by SivaKesava1** [yadifa/yadifa#11]
Hi,

This is related to if 'A CNAME B' exists in a zone, but B (related to the same zone) does not exist, then the return code should be NXDOMAIN.  [RFC 6604](https://tools.ietf.org/html/rfc6604#section-3) mentions that 
> When chains are followed, the RCODE in the ultimate DNS response MUST BE set based on the final query cycle leading to that
>       response.

YADIFA already does not follow CNAME chains, as mentioned in #10, but even for a single CNAME one, it does not return the rcode properly.
 
Consider the following sample zone file:

|  	|  	|  	|  	|
|-	|-	|-	|-	|
| example.com. 	| 500 | SOA 	| ns1.outside.com. root.example.com. 3 604800 86400 2419200 604800 	|
| example.com. 	| 500 | NS 	| ns1.outside.com.  	|
| b.c.example.com. 	| 500 | CNAME | c.c.example.com.  	|

For the query _<b.c.example.com. , A>_, the YADIFA server returns the following response:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "b.c.campus.edu. IN A",
          ";ANSWER",
          "b.c.example.com. 500 IN CNAME c.c.example.com.",
          ";AUTHORITY",
          ";ADDITIONAL"
```
**Expected**:
The expected response is the same as above except that the `rcode` should be `NXDOMAIN.`

**Comment by edfeu** [comment]
Hello,

Thank you for reporting this issue.
It is related to https://github.com/yadifa/yadifa/issues/10
It is now fixed internally and the correction will be made available with the next update on github.
It should happen early next week.
