### ISSUE TITLE
Why is "*" considered as an invalid charset in Rdata?

### ISSUE THREAD

**Issue by SivaKesava1** [yadifa/yadifa#13]
Hello again,

"\*" as a label is accepted in the domain name but not in the Rdata by Yadifa.  I compared it with other implementations like Bind, PowerDNS, and Nsd to ensure that I have not missed some RFC rules. All of those implementations accept a "*" as a label in Rdata also. I am kind of curious as to why this distinction is made by yadifa. 

**Details**:
Consider this zone file:
  |   |   |  
-- | -- | -- | --
example.com. | 500 | SOA | ns1.outside.com. root.example.com. 3 604800 86400 2419200 604800
example.com. | 500 | NS | ns1.outside.com.
*.example.com. | 500 | CNAME | ww.example.com.
foo.example.com. | 500 | CNAME | bar.*.outside.com.

When there are only the first three resource records, then Yadifa accepts the zone file and answers queries as expected. But, when the fourth record is added, the following error is logged in the logs:
```
zone load: reading record #3 of zone campus.edu.: could not parse rdata for foo. example.com. IN CNAME from line "foo.example.com.
     500 IN  CNAME      bar.*.outside.com.
": INVALID_CHARSET
```

_Thank you for responding to all my reports so far._

**Comment by yadifa** [comment]
By default YADIFA ensures that FQDNs are made by the original dns character set plus the underscore. If the full ascii7 set is required, it needs to be built with the --enable-full-ascii7 option.
