### ISSUE TITLE
Dynamic update requests with unfulfilled prerequisites always returns SERVFAIL 

### ISSUE THREAD

**Issue by dextercd** [yadifa/yadifa#15]
Dynamic update requests are supposed to give an indication of what kind of prerequisite failed by returning error codes like:

- NXDOMAIN,
- YXDOMAIN,
- YXRRSET,
- NXRRSET

But currently an update request with a failing prerequisite always returns SERVFAIL, which is only supposed to be used to indicate an internal error.

It seems like the `dynupdate_check_prerequisites` does correctly identify and return these error codes, but that the caller `database_update` doesn't use this info.

When I apply this patch to `database.c` I get the result that I expected.

```diff
--- a/sbin/yadifad/database.c
+++ b/sbin/yadifad/database.c
@@ -1375,7 +1375,14 @@ database_update(zdb *database, message_data *mesg)
 
                                     log_warn("database: update: %{dnsname}: prerequisites not met", message_get_canonised_fqdn(mesg));
 
-                                    message_set_status(mesg, FP_RCODE_SERVFAIL);
+                                    if((ret & 0xffff0000) == RCODE_ERROR_BASE)
+                                    {
+                                        message_set_status(mesg, RCODE_ERROR_GETCODE(ret));
+                                    }
+                                    else
+                                    {
+                                        message_set_status(mesg, FP_RCODE_SERVFAIL);
+                                    }
                                 }
 
                                 zdb_zone_double_unlock(zone, ZDB_ZONE_MUTEX_SIMPLEREADER, ZDB_ZONE_MUTEX_DYNUPDATE);
```

**Comment by yadifa** [comment]
Thank you for pointing this out.
The error code discrimination was indeed missing on this code path.  Your fix is correct.
The fix using the message_* set of functions should be committed next Monday.

**Comment by dextercd** [comment]
Great to hear this fix will get integrated. Keep up the good work!
