### ISSUE TITLE
Unchecked malloc's?

### ISSUE THREAD

**Issue by icefoxen** [yadifa/yadifa#3]
I was just randomly browsing the codebase and it occurred to me to look for unchecked mallocs.  I seem to have found two:

https://github.com/yadifa/yadifa/blob/b5e350c951cd45c654090fb910f385bb5c828a13/lib/dnscore/src/list-sl-debug.c#L66

https://github.com/yadifa/yadifa/blob/b5e350c951cd45c654090fb910f385bb5c828a13/lib/dnscore/src/ptr_set_debug.c#L115

These are apparently in debug libraries so I don't know if they matter.  The non-debug versions of those files appear to either not have corresponding functions or use a `MALLOC_OR_DIE` macro of one kind or another.

**Comment by yadifa** [comment]
Yes, this code is specifically made so it does not go through the various debugging/integrity checks.
